### PR TITLE
more_mime_types

### PR DESCRIPTION
**Pull request by dephillipsmichael**
Added more mime types that can be automatically converted.
Is there anyway to inject these?  If not, I hope we can add these.

### CODE REVIEW

**Comment by dephillipsmichael** [comment]
I don't see how adding a few branches to an existing conditional could break the build?  Looking into why CI failed....

**Comment by dephillipsmichael** [comment]
I see the test that's failing, but I can't run tests locally for more info because of Xcode can't find mogenerator?

**Comment by Erin-Mounts** [comment]
so, pull mogenerator from my fork here: https://github.com/Erin-Mounts/mogenerator.git then open the project file and build it; that should install it where the build script is looking for it.

**Comment by dephillipsmichael** [comment]
Closing until we get back to Resilience

**Pull request closed without merging**
