### PR TITLE
Activity caching bug

### PR DESCRIPTION
**Pull request by Erin-Mounts**
Since Bridge doesn't give us an identifier to distinguish one ResourceList from another, we need to create one that maps to the API used to retrieve it... and, critically, we need to also store this artificial identifier to CoreData when saving the ResourceList there, even though it's not part of the Bridge JSON. Otherwise we'll never find it again once the in-memory cache is purged (e.g. app restart).

### CODE REVIEW

**Comment by dephillipsmichael** [comment]
Looks good.  Thanks for fixing!

**Comment by dephillipsmichael** [comment]
I pointed at the fix, and I am getting this crash once I complete a factors activity...

2017-05-30 20:02:26.232 elevateMS[63657:5502930] *** Assertion failure in -[SBBCacheManager managedObjectOfEntity:withId:atKeyPath:], /Users/TheMDP/Work/Development/iOS/ElevateMs/BridgeAppSDK/BridgeSDK/BridgeSDK/Internal/SBBCacheManager.m:450
2017-05-30 20:02:26.233 elevateMS[63657:5502930] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '2 ResourceList objects found with listID__ == @"ScheduledActivity"'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107580b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000106fe5141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000107584cf2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000106b7f3b6 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   BridgeSDK                           0x00000001068347d5 -[SBBCacheManager managedObjectOfEntity:withId:atKeyPath:] + 1493
	5   BridgeSDK                           0x0000000106831313 __69-[SBBCacheManager cachedObjectOfType:withId:createIfMissing:created:]_block_invoke + 195
	6   CoreData                            0x000000010fa17b52 developerSubmittedBlockToNSManagedObjectContextPerform + 178
	7   CoreData                            0x000000010fa17a1f -[NSManagedObjectContext performBlockAndWait:] + 239
	8   BridgeSDK                           0x000000010683100e -[SBBCacheManager cachedObjectOfType:withId:createIfMissing:created:] + 990
	9   BridgeSDK                           0x0000000106830bf4 -[SBBCacheManager cachedObjectOfType:withId:createIfMissing:] + 148
	10  BridgeSDK                           0x00000001067e745c -[SBBActivityManager cachedTasksFromCacheManager:] + 156
	11  BridgeSDK                           0x00000001067e83c7 __97-[SBBActivityManager getScheduledActivitiesForDaysAhead:daysBehind:cachingPolicy:withCompletion:]_block_invoke_2 + 103
	12  CoreData                            0x000000010fa17b52 developerSubmittedBlockToNSManagedObjectContextPerform + 178
	13  libdispatch.dylib                   0x000000010db9905c _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x000000010db7794f _dispatch_queue_serial_drain + 221
	15  libdispatch.dylib                   0x000000010db78669 _dispatch_queue_invoke + 1084
	16  libdispatch.dylib                   0x000000010db7aec4 _dispatch_root_queue_drain + 634
	17  libdispatch.dylib                   0x000000010db7abef _dispatch_worker_thread3 + 123
	18  libsystem_pthread.dylib             0x000000010df305a2 _pthread_wqthread + 1299
	19  libsystem_pthread.dylib             0x000000010df3007d start_wqthread + 13

**Comment by Erin-Mounts** [comment]
Gah. Looking into it now.

**Comment by syoung-smallwisdom** [comment]
@Erin-Mounts Can you let me know when there is an update? Thanks!

**Comment by Erin-Mounts** [comment]
there's an update

**Comment by syoung-smallwisdom** [comment]
Looks good

**Comment by dephillipsmichael** [comment]
Yes, works for me now too.  Looks good.

**Pull request merged**
