### PR TITLE
SurveyElement.rules -> .afterRules

### PR DESCRIPTION
**Pull request by Erin-Mounts**

### CODE REVIEW

**Comment by syoung-smallwisdom** [comment]
Um... this is going to break BridgeAppSDK, isn't it?

**Comment by Erin-Mounts** [comment]
I’m changing BridgeAppSDK to use the v4 activities APIs as we “speak”, so I could just change that property name while I’m at it—or is there more to it than that?

**Comment by Erin-Mounts** [comment]
also--adding rules to SurveyElement already breaks BridgeAppSDK; changing it to afterRules would keep it from breaking: 
"/Users/erin/Development/Sage/BridgeAppSDK/BridgeAppSDK/SBASurveyItem+Bridge.swift:249:16: Property 'rules' with type '[SBASurveyRuleItem]?' cannot override a property with type '[Any]!'"

**Comment by Erin-Mounts** [comment]
to clarify--I'm not changing the rules object down in the constraints, just the new one I added at the SurveyElement (question or information) level that BridgeAppSDK wasn't aware of yet anyway.

**Pull request merged**
